spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      prod:
        - common

---

spring:
  config:
    activate:
      on-profile: common

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/pharmacy
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
#    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: create
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show-sql: true

---

spring:
  config:
    activate:
      on-profile: prod